CREATE TABLE `durable_workflow` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `kind` VARCHAR(191) NOT NULL,
    `version` INT NOT NULL,
    `input_json` LONGTEXT NOT NULL,
    `state_json` LONGTEXT NOT NULL,
    `state_version` INT NOT NULL DEFAULT 1,
    `status` VARCHAR(32) NOT NULL,
    `result_json` LONGTEXT NULL,
    `error_category` VARCHAR(64) NULL,
    `error_message` VARCHAR(2048) NULL,
    `wait_kind` VARCHAR(32) NULL,
    `wait_reference_id` BIGINT NULL,
    `available_at` BIGINT NOT NULL,
    `activation_attempts` INT NOT NULL DEFAULT 0,
    `max_activation_attempts` INT NOT NULL,
    `consecutive_continuations` INT NOT NULL DEFAULT 0,
    `lease_owner` VARCHAR(191) NULL,
    `lease_token` VARCHAR(36) NULL,
    `lease_expires_at` BIGINT NULL,
    `deduplication_key` VARCHAR(191) NULL,
    `schedule_run_id` BIGINT NULL,
    `root_workflow_id` BIGINT NULL,
    `restarted_from_workflow_id` BIGINT NULL,
    `parent_workflow_id` BIGINT NULL,
    `parent_command_sequence` INT NULL,
    `command_sequence` INT NOT NULL DEFAULT 0,
    `delivered_event_sequence` INT NOT NULL DEFAULT 0,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `completed_at` BIGINT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_durable_workflow_deduplication` (`kind`, `deduplication_key`),
    UNIQUE KEY `uq_durable_workflow_restart` (`restarted_from_workflow_id`),
    KEY `idx_durable_workflow_claim` (`status`, `available_at`, `lease_expires_at`, `id`),
    KEY `idx_durable_workflow_version` (`kind`, `version`, `status`),
    KEY `idx_durable_workflow_root` (`root_workflow_id`),
    KEY `idx_durable_workflow_parent` (`parent_workflow_id`),
    KEY `idx_durable_workflow_wait` (`wait_kind`, `wait_reference_id`, `status`),
    CONSTRAINT `fk_durable_workflow_root` FOREIGN KEY (`root_workflow_id`) REFERENCES `durable_workflow` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_durable_workflow_restart` FOREIGN KEY (`restarted_from_workflow_id`) REFERENCES `durable_workflow` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_durable_workflow_parent` FOREIGN KEY (`parent_workflow_id`) REFERENCES `durable_workflow` (`id`) ON DELETE RESTRICT,
    CHECK (`version` > 0),
    CHECK (`state_version` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_workflow_event` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `workflow_id` BIGINT NOT NULL,
    `sequence` INT NOT NULL,
    `delivery_sequence` INT NULL,
    `event_type` VARCHAR(64) NOT NULL,
    `metadata_json` LONGTEXT NULL,
    `actor_type` VARCHAR(32) NULL,
    `actor_id` VARCHAR(191) NULL,
    `reason` VARCHAR(2048) NULL,
    `created_at` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_durable_workflow_event_sequence` (`workflow_id`, `sequence`),
    UNIQUE KEY `uq_durable_workflow_event_delivery` (`workflow_id`, `delivery_sequence`),
    KEY `idx_durable_workflow_event_timeline` (`workflow_id`, `created_at`, `id`),
    CONSTRAINT `fk_durable_workflow_event_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `durable_workflow` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_activity` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `workflow_id` BIGINT NOT NULL,
    `command_sequence` INT NOT NULL,
    `replacement_number` INT NOT NULL DEFAULT 0,
    `kind` VARCHAR(191) NOT NULL,
    `version` INT NOT NULL,
    `topic` VARCHAR(191) NOT NULL,
    `payload_json` LONGTEXT NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `available_at` BIGINT NOT NULL,
    `max_attempts` INT NOT NULL,
    `attempt_count` INT NOT NULL DEFAULT 0,
    `timeout_millis` BIGINT NOT NULL,
    `lease_duration_millis` BIGINT NOT NULL,
    `retry_policy_json` VARCHAR(512) NOT NULL,
    `operation_key` VARCHAR(191) NULL,
    `provider_result_json` LONGTEXT NULL,
    `last_error_category` VARCHAR(64) NULL,
    `last_error_message` VARCHAR(2048) NULL,
    `lease_owner` VARCHAR(191) NULL,
    `lease_token` VARCHAR(36) NULL,
    `lease_expires_at` BIGINT NULL,
    `root_activity_id` BIGINT NULL,
    `replaces_activity_id` BIGINT NULL,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    `completed_at` BIGINT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_durable_activity_command` (`workflow_id`, `command_sequence`, `replacement_number`),
    KEY `idx_durable_activity_claim` (`topic`, `status`, `available_at`, `lease_expires_at`, `id`),
    KEY `idx_durable_activity_version` (`kind`, `version`, `status`),
    KEY `idx_durable_activity_root` (`root_activity_id`),
    KEY `idx_durable_activity_topic_completed` (`topic`, `completed_at`),
    CONSTRAINT `fk_durable_activity_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `durable_workflow` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_durable_activity_root` FOREIGN KEY (`root_activity_id`) REFERENCES `durable_activity` (`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_durable_activity_replacement` FOREIGN KEY (`replaces_activity_id`) REFERENCES `durable_activity` (`id`) ON DELETE RESTRICT,
    CHECK (`version` > 0),
    CHECK (`max_attempts` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_activity_attempt` (
    `activity_id` BIGINT NOT NULL,
    `attempt_number` INT NOT NULL,
    `worker_id` VARCHAR(191) NOT NULL,
    `lease_token` VARCHAR(36) NOT NULL,
    `started_at` BIGINT NOT NULL,
    `heartbeat_at` BIGINT NOT NULL,
    `finished_at` BIGINT NULL,
    `outcome` VARCHAR(32) NULL,
    `error_category` VARCHAR(64) NULL,
    `error_message` VARCHAR(2048) NULL,
    `provider_result_json` LONGTEXT NULL,
    PRIMARY KEY (`activity_id`, `attempt_number`),
    KEY `idx_durable_activity_attempt_started` (`started_at`),
    CONSTRAINT `fk_durable_activity_attempt_activity` FOREIGN KEY (`activity_id`) REFERENCES `durable_activity` (`id`) ON DELETE RESTRICT,
    CHECK (`attempt_number` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_progress_event` (
    `activity_id` BIGINT NOT NULL,
    `attempt_number` INT NOT NULL,
    `sequence` INT NOT NULL,
    `code` VARCHAR(64) NOT NULL,
    `description` TEXT NOT NULL,
    `description_bytes` INT NOT NULL,
    `completed_units` BIGINT NULL,
    `total_units` BIGINT NULL,
    `severity` VARCHAR(16) NOT NULL,
    `metadata_json` TEXT NULL,
    `created_at` BIGINT NOT NULL,
    PRIMARY KEY (`activity_id`, `attempt_number`, `sequence`),
    CONSTRAINT `fk_durable_progress_attempt` FOREIGN KEY (`activity_id`, `attempt_number`) REFERENCES `durable_activity_attempt` (`activity_id`, `attempt_number`) ON DELETE RESTRICT,
    CHECK (`sequence` > 0 AND `sequence` <= 100),
    CHECK (`description_bytes` <= 2048)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_approval` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `workflow_id` BIGINT NOT NULL,
    `command_sequence` INT NOT NULL,
    `kind` VARCHAR(191) NOT NULL,
    `version` INT NOT NULL,
    `prompt_metadata_json` TEXT NOT NULL,
    `validation_schema_json` TEXT NOT NULL,
    `validation_version` INT NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `requested_at` BIGINT NOT NULL,
    `expires_at` BIGINT NULL,
    `decision_payload_json` TEXT NULL,
    `decided_by` INT NULL,
    `operator_reason` VARCHAR(2048) NULL,
    `resolved_at` BIGINT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_durable_approval_command` (`workflow_id`, `command_sequence`),
    KEY `idx_durable_approval_pending` (`status`, `expires_at`, `id`),
    CONSTRAINT `fk_durable_approval_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `durable_workflow` (`id`) ON DELETE RESTRICT,
    CHECK (`version` > 0),
    CHECK (`validation_version` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_schedule_state` (
    `schedule_key` VARCHAR(191) NOT NULL,
    `definition_fingerprint` VARCHAR(64) NOT NULL,
    `definition_version` INT NOT NULL,
    `next_local_occurrence` VARCHAR(191) NOT NULL,
    `next_occurrence_at` BIGINT NOT NULL,
    `last_materialized_at` BIGINT NULL,
    `paused_at` BIGINT NULL,
    `paused_by` INT NULL,
    `pause_reason` VARCHAR(2048) NULL,
    `created_at` BIGINT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    PRIMARY KEY (`schedule_key`),
    KEY `idx_durable_schedule_due` (`paused_at`, `next_occurrence_at`, `schedule_key`),
    CHECK (`definition_version` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_schedule_run` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `schedule_key` VARCHAR(191) NOT NULL,
    `local_occurrence` VARCHAR(191) NOT NULL,
    `scheduled_for` BIGINT NOT NULL,
    `materialized_at` BIGINT NOT NULL,
    `status` VARCHAR(32) NOT NULL,
    `reason` VARCHAR(2048) NULL,
    `actor_id` INT NULL,
    `workflow_id` BIGINT NULL,
    `created_at` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_durable_schedule_run_occurrence` (`schedule_key`, `local_occurrence`),
    KEY `idx_durable_schedule_run_timeline` (`schedule_key`, `scheduled_for`, `id`),
    CONSTRAINT `fk_durable_schedule_run_state` FOREIGN KEY (`schedule_key`) REFERENCES `durable_schedule_state` (`schedule_key`) ON DELETE RESTRICT,
    CONSTRAINT `fk_durable_schedule_run_workflow` FOREIGN KEY (`workflow_id`) REFERENCES `durable_workflow` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `durable_topic_lock` (
    `topic` VARCHAR(191) NOT NULL,
    `max_concurrency` INT NOT NULL,
    `updated_at` BIGINT NOT NULL,
    PRIMARY KEY (`topic`),
    CHECK (`max_concurrency` > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
